version: '2'

services:
  nginx:
    build: ./nginx
    image: sba-eli-proxy
    ports:
      - 80:80
    links:
      - front-end
      - service-layer
  front-end:
    build: ./front-end
    image: sba-eli-ui
    environment:
      - REACT_APP_SERVICE_HOST=http://localhost
  service-layer:
    build: ./service-layer
    image: sba-eli-api
    ports:
      - 3000:3000
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
