version: '2'

services:
  proxy:
    build : ./proxy
    image: ${ECR_URI}/sba-eli-proxy:${TAG}
    ports:
      - "80:80"
      - "8080:8080"
    command: --api --logLevel=INFO
    logging:
      driver: awslogs
      options:
        awslogs-group: sba-eli
        awslogs-region: us-east-1
        awslogs-stream-prefix: proxy
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - BRANCH
      - DOMAIN

  front-end:
    image: ${ECR_URI}/sba-eli-ui:${TAG}
    ports:
      - "8000:8000"
    environment:
      - REACT_APP_SERVICE_HOST=http://${BRANCH}.${DOMAIN}:3000
    logging:
      driver: awslogs
      options:
        awslogs-group: sba-eli
        awslogs-region: us-east-1
        awslogs-stream-prefix: ui
    labels:
      - traefik.frontend.rule=PathPrefixStrip:/
      # - traefik.backend=client
      - traefik.port=8000

  service-layer:
    image: ${ECR_URI}/sba-eli-api:${TAG}
    ports:
      - "3000:3000"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    logging:
      driver: awslogs
      options:
        awslogs-group: sba-eli
        awslogs-region: us-east-1
        awslogs-stream-prefix: api
    labels:
      - traefik.frontend.rule=PathPrefix:/api
      # - traefik.backend=api
      - traefik.port=3000
