# Add configuration values here to .env 

CANVAS_ACCOUNT_ID: <%= ENV["CANVAS_ACCOUNT_ID"] %>
CANVAS_NAMESPACE: <%= ENV["CANVAS_NAMESPACE"] %>
CANVAS_HOST:  <%= ENV["CANVAS_HOST"] %>
CANVAS_URI:  <%= ENV["CANVAS_URI"] %>
AWS_ACCESS_KEY_ID: <%= ENV["AWS_ACCESS_KEY_ID"] %>
AWS_SECRET_ACCESS_KEY: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
AWS_REGION: <%= ENV["AWS_REGION"] %>>
AWS_COGNITO_USER_POOL_ID:  <%= ENV["AWS_COGNITO_USER_POOL_ID"] %>
AWS_COGNITO_CLIENT_ID:  <%= ENV["AWS_COGNITO_CLIENT_ID"] %>
CANVAS_TOKEN: <%= ENV["CANVAS_TOKEN"] %>
CANVAS_CLIENT_ID:  <%= ENV["CANVAS_CLIENT_ID"] %>
CANVAS_CLIENT_SECRET: <%= ENV["CANVAS_CLIENT_SECRET"] %>
