version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: ecsTaskExecutionRole
  task_size:
    cpu_limit: 512
    mem_limit: 2GB
  services:
    nginx:
      essential: true
    front-end:
      essential: true
      environment:
        - name: REACT_APP_SERVICE_HOST
        - value: ${ELB_DNS}
    service-layer:
      essential: true

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - ${PUBLIC_SUBNET_ONE}
        - ${PUBLIC_SUBNET_TWO}
      security_groups:
        - ${ECS_SECURITY_GROUP}
      assign_public_ip: ENABLED
