# enable logging on the debug level
logLevel = "DEBUG"

# log requests. It defaults to logging to stdout
# the filters are for logging only requests that get certain http status codes, in this case we log everything
[accessLog]
  [accessLog.filters]
    statusCodes = ["0-600"]

[api]
address = ":8080"
readOnly = true

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

################################################################
# ECS Provider
################################################################

# Enable ECS Provider.

[ecs]
clusters = ["CLUSTER"]
watch = true
domain = "BRANCH.DOMAIN"
autoDiscoverClusters = false
refreshSeconds = 15
exposedByDefault = true
region = "AWS_DEFAULT_REGION"
accessKeyID = "AWS_ACCESS_KEY_ID"
secretAccessKey = "AWS_SECRET_ACCESS_KEY"
